"""PDF utility functions using PyMuPDF.

実装は用途別モジュール(common/annotations/rendering/pages/export/printing)に
分割されている。既存の import 面(プライベート名含む)を維持するため、
このパッケージ __init__ が旧 pdf_utils モジュールの全シンボルを再エクスポートする。
"""
# テストが pdf_utils.shutil.move を monkeypatch できるよう属性として公開する
import shutil

from .common import (
    PdfWritePermissionError,
    _PixmapCache,
    _get_file_cache_token,
    _is_permission_denied_error,
    _pixmap_cache,
    _save_document_in_place,
    clear_pixmap_cache,
    clear_pixmap_cache_for_path,
    logger,
)

from .annotations import (
    AnyAnnotData,
    FreeTextAnnotData,
    JUSTICEPDF_FREETEXT_SUBJECT_PREFIX,
    JUSTICEPDF_MARKUP_SUBJECT_PREFIX,
    JUSTICEPDF_NOTE_SUBJECT_PREFIX,
    JUSTICEPDF_SHAPE_SUBJECT_PREFIX,
    MarkupType,
    NOTE_ICON_PDF_SIZE,
    NoteAnnotData,
    ShapeAnnotData,
    ShapeType,
    TextMarkupAnnotData,
    _AnnotFamily,
    _CSS_BORDER_RE,
    _CSS_DECL_RE,
    _DA_COLOR_RE,
    _DA_FONT_RE,
    _FLOAT_RE,
    _FREETEXT_FAMILY,
    _MARKUP_ANNOT_TYPES,
    _MARKUP_FAMILY,
    _MARKUP_TYPE_TO_PDF,
    _NOTE_FAMILY,
    _SHAPE_ANNOT_TYPES,
    _SHAPE_FAMILY,
    _add_freetext_annot_to_page,
    _add_markup_annot_to_page,
    _add_note_annot_to_page,
    _add_shape_annot_to_page,
    _bracket_vertices_curly,
    _bracket_vertices_horizontal,
    _bracket_vertices_round,
    _bracket_vertices_square,
    _build_richtext_style,
    _callout_box_attach,
    _color_to_css,
    _compute_bracket_vertices,
    _compute_shape_vertices,
    _create_annot,
    _css_color_to_rgb,
    _css_font_to_pdf,
    _decode_markup_metadata,
    _decode_note_metadata,
    _decode_prefixed_json,
    _decode_shape_metadata,
    _decode_subject_metadata,
    _delete_annot,
    _ellipse_vertices,
    _encode_markup_metadata,
    _encode_note_metadata,
    _encode_prefixed_json,
    _encode_shape_metadata,
    _encode_subject_metadata,
    _extract_freetext_data,
    _extract_markup_data,
    _extract_note_data,
    _extract_shape_data,
    _extract_text_from_rc,
    _fix_rc_leading_whitespace,
    _get_page_annot_xref_order,
    _line_ending_code,
    _line_endpoints_from_data,
    _list_annots,
    _normalize_color,
    _page_numbers_for,
    _parse_css_declarations,
    _parse_da,
    _parse_float_array,
    _pdf_font_to_css,
    _rectangle_vertices,
    _replace_annot,
    _rotate_point,
    _rotate_vertices,
    _set_page_annot_xref_order,
    _triangle_vertices,
    create_bracket_pair,
    create_callout,
    create_freetext_annot,
    create_markup_annot,
    create_note_annot,
    create_shape_annot,
    delete_annot_group,
    delete_freetext_annot,
    delete_markup_annot,
    delete_note_annot,
    delete_shape_annot,
    get_annot_xref_order,
    list_annot_group,
    list_freetext_annots,
    list_markup_annots,
    list_note_annots,
    list_shape_annots,
    reorder_annot_on_page,
    replace_freetext_annot,
    replace_markup_annot,
    replace_note_annot,
    replace_shape_annot,
    set_annot_xref_order,
)

from .rendering import (
    _pixmap_to_qpixmap,
    _render_page_pixmap,
    get_page_chars,
    get_page_count,
    get_page_links,
    get_page_pixmap,
    get_page_size_points,
    get_page_thumbnail,
    get_page_words,
    get_pdf_card_info,
    render_page_thumbnails_batch,
    search_text_in_pdf,
)

from .pages import (
    TocEntry,
    _file_bookmark_title,
    _file_toc_entries,
    _offset_toc_entries,
    create_empty_pdf,
    extract_pages,
    get_pdf_metadata_title,
    get_pdf_toc,
    insert_pages,
    merge_paths_to_pdf,
    merge_pdfs_in_place,
    normalize_toc,
    remove_pages,
    reorder_pages,
    rotate_pages,
    update_pdf_metadata_title,
    update_pdf_toc,
)

from .export import (
    _downsample_images,
    _downsample_images_inner,
    _render_page_to_image_bytes,
    export_pages_as_images,
    export_pdf_compressed,
    images_to_pdf,
    rasterize_pdf,
)

from .printing import (
    PrintSettings,
    _PRINT_MAX_RASTER_PX,
    _draw_page_into_rect,
    _page_is_landscape,
    build_flat_index,
    nup_grid,
    parse_page_range,
    print_pdfs,
)
